=== bob-collective/bob/tokenlist/token.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Token Schema",
  "type": "object",
  "definitions": {
    "ChainProperties": {
      "type": "object",
      "properties": {
        "name": {
          "$ref": "#/definitions/Name"
        },
        "symbol": {
          "$ref": "#/definitions/Symbol"
        },
        "address": {
          "$ref": "#/definitions/Address"
        },
        "bridge": {
          "type": "object",
          "properties": {
            "bob": {
              "$ref": "#/definitions/Address"
            },
            "bob-sepolia": {
              "$ref": "#/definitions/Address"
            },
            "ethereum": {
              "$ref": "#/definitions/Address"
            },
            "sepolia": {
              "$ref": "#/definitions/Address"
            },
            "bnb-smart-chain": {
              "$ref": "#/definitions/Address"
            },
            "base": {
              "$ref": "#/definitions/Address"
            },
            "op-mainnet": {
              "$ref": "#/definitions/Address"
            },
            "arbitrum-one": {
              "$ref": "#/definitions/Address"
            },
            "polygon": {
              "$ref": "#/definitions/Address"
            },
            "avalanche": {
              "$ref": "#/definitions/Address"
            },
            "unichain": {
              "$ref": "#/definitions/Address"
            },
            "sonic": {
              "$ref": "#/definitions/Address"
            },
            "sei-network": {
              "$ref": "#/definitions/Address"
            },
            "soneium-mainnet": {
              "$ref": "#/definitions/Address"
            },
            "berachain": {
              "$ref": "#/definitions/Address"
            },
            "swellchain": {
              "$ref": "#/definitions/Address"
            },
            "telos": {
              "$ref": "#/definitions/Address"
            }
          }
        },
        "overrides": {
          "type": "object",
          "properties": {
            "name": {
              "$ref": "#/definitions/Name"
            },
            "symbol": {
              "$ref": "#/definitions/Symbol"
            }
          }
        }
      },
      "required": ["address"],
      "additionalProperties": false
    },
    "Address": {
      "type": "string",
      "description": "The checksummed address of the token on the specified chain ID",
      "pattern": "^(0x[a-fA-F0-9]{40}|[1-9A-HJ-NP-Za-km-z]{32,44})$",
      "examples": [
        "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
        "So11111111111111111111111111111111111111112"
      ]
    },
    "Name": {
      "type": "string",
      "description": "The name of the token",
      "minLength": 0,
      "maxLength": 60,
      "anyOf": [
        {
          "const": ""
        },
        {
          "pattern": "^[ \\S+]+$"
        }
      ],
      "examples": ["USD Coin"]
    },
    "Symbol": {
      "type": "string",
      "description": "The symbol for the token",
      "minLength": 0,
      "maxLength": 20,
      "anyOf": [
        {
          "const": ""
        },
        {
          "pattern": "^\\S+$"
        }
      ],
      "examples": ["USDC"]
    }
  },
  "properties": {
    "name": {
      "$ref": "#/definitions/Name"
    },
    "symbol": {
      "$ref": "#/definitions/Symbol"
    },
    "decimals": {
      "type": "integer",
      "description": "The number of decimals for the token balance",
      "minimum": 0,
      "maximum": 255,
      "examples": [18]
    },
    "description": {
      "type": "string",
      "description": "A description of the token or project (can be empty)"
    },
    "website": {
      "type": "string",
      "description": "URL of the project's website",
      "format": "uri",
      "pattern": "^https?://.+"
    },
    "twitter": {
      "type": "string",
      "description": "Twitter handle of the project, e.g., '@gobob'",
      "pattern": "^@?[A-Za-z0-9_]+$"
    },
    "tokens": {
      "type": "object",
      "description": "Network-specific token addresses",
      "properties": {
        "bob": {
          "$ref": "#/definitions/ChainProperties"
        },
        "bob-sepolia": {
          "$ref": "#/definitions/ChainProperties"
        },
        "ethereum": {
          "$ref": "#/definitions/ChainProperties"
        },
        "sepolia": {
          "$ref": "#/definitions/ChainProperties"
        },
        "bnb-smart-chain": {
          "$ref": "#/definitions/ChainProperties"
        },
        "base": {
          "$ref": "#/definitions/ChainProperties"
        },
        "op-mainnet": {
          "$ref": "#/definitions/ChainProperties"
        },
        "arbitrum-one": {
          "$ref": "#/definitions/ChainProperties"
        },
        "polygon": {
          "$ref": "#/definitions/ChainProperties"
        },
        "avalanche": {
          "$ref": "#/definitions/ChainProperties"
        },
        "unichain": {
          "$ref": "#/definitions/ChainProperties"
        },
        "sonic": {
          "$ref": "#/definitions/ChainProperties"
        },
        "sei-network": {
          "$ref": "#/definitions/ChainProperties"
        },
        "soneium-mainnet": {
          "$ref": "#/definitions/ChainProperties"
        },
        "berachain": {
          "$ref": "#/definitions/ChainProperties"
        },
        "swellchain": {
          "$ref": "#/definitions/ChainProperties"
        },
        "telos": {
          "$ref": "#/definitions/ChainProperties"
        }
      },
      "minProperties": 1,
      "additionalProperties": false
    }
  },
  "required": ["name", "symbol", "decimals", "tokens"],
  "additionalProperties": false
}

=== bob-collective/bob/tokenlist/data/DLLR/data.json
{
  "name": "Sovryn DLLR",
  "symbol": "DLLR",
  "decimals": 18,
  "tokens": {
    "ethereum": {
      "address": "0xbdBb63F938c8961AF31eaD3deBa5C96e6A323DD1",
      "bridge": {
        "bob": "0x3F6cE1b36e5120BBc59D0cFe8A5aC8b6464ac1f7"
      }
    },
    "bob": {
      "address": "0xf3107eEC1e6F067552C035FD87199e1A5169CB20",
      "bridge": {
        "ethereum": "0x4200000000000000000000000000000000000010"
      }
    }
  }
}

=== bob-collective/bob/tokenlist/data/tBTC/data.json
{
  "name": "tBTC v2",
  "symbol": "tBTC",
  "decimals": 18,
  "description": "Decentralized, Permissionless Bitcoin Bridge",
  "website": "https://threshold.network",
  "twitter": "@TheTNetwork",
  "tokens": {
    "ethereum": {
      "address": "0x18084fbA666a33d37592fA2633fD49a74DD93a88",
      "bridge": {
        "bob": "0x3F6cE1b36e5120BBc59D0cFe8A5aC8b6464ac1f7"
      }
    },
    "sepolia": {
      "address": "0x517f2982701695D4E52f1ECFBEf3ba31Df470161"
    },
    "bob": {
      "address": "0xBBa2eF945D523C4e2608C9E1214C2Cc64D4fc2e2",
      "bridge": {
        "ethereum": "0x4200000000000000000000000000000000000010"
      }
    },
    "bob-sepolia": {
      "name": "BOB tBTC v2",
      "address": "0xD23F06550b0A7bC98B20eb81D4c21572a97598FA"
    },
    "op-mainnet": {
      "name": "Optimism tBTC v2",
      "address": "0x6c84a8f1c29108F47a79964b5Fe888D4f4D0dE40"
    },
    "arbitrum-one": {
      "name": "Arbitrum tBTC v2",
      "address": "0x6c84a8f1c29108F47a79964b5Fe888D4f4D0dE40"
    },
    "base": {
      "address": "0x236aa50979D5f3De3Bd1Eeb40E81137F22ab794b"
    }
  }
}

=== bob-collective/bob/tokenlist/data/T/data.json
{
  "name": "Threshold Network Token",
  "symbol": "T",
  "decimals": 18,
  "description": "Threshold Network is the home of $tBTC, proxy re-encryption #PRE, $thUSD, and all threshold cryptography.",
  "website": "https://threshold.network",
  "twitter": "@TheTNetwork",
  "tokens": {
    "ethereum": {
      "address": "0xCdF7028ceAB81fA0C6971208e83fa7872994beE5",
      "bridge": {
        "bob": "0x3F6cE1b36e5120BBc59D0cFe8A5aC8b6464ac1f7"
      }
    },
    "bob": {
      "address": "0xF14e82E192a36Df7d09Fe726F6ECF70310f73438",
      "bridge": {
        "ethereum": "0x4200000000000000000000000000000000000010"
      }
    },
    "op-mainnet": {
      "address": "0x747e42Eb0591547a0ab429B3627816208c734EA7"
    }
  }
}

=== bob-collective/bob/tokenlist/data/SolvBTC/data.json
{
  "name": "Solv BTC",
  "symbol": "SolvBTC",
  "decimals": 18,
  "description": "",
  "website": "https://app.solv.finance/",
  "twitter": "@SolvProtocol",
  "tokens": {
    "ethereum": {
      "address": "0x7A56E1C57C7475CCf742a1832B028F0456652F97"
    },
    "bob": {
      "address": "0x541FD749419CA806a8bc7da8ac23D346f2dF8B77"
    },
    "arbitrum-one": {
      "address": "0x3647c54c4c2c65bc7a2d63c0da2809b399dbbdc0"
    },
    "avalanche": {
      "address": "0xbc78d84ba0c46dfe32cf2895a19939c86b81a777"
    },
    "base": {
      "address": "0x3b86ad95859b6ab773f55f8d94b4b9d443ee931f"
    },
    "polygon": {
      "address": "0xae4efbc7736f963982aacb17efa37fcbab924cb3"
    },
    "bnb-smart-chain": {
      "address": "0x4aae823a6a0b376de6a78e74ecc5b079d38cbcf7"
    }
  }
}

=== bob-collective/bob/tokenlist/data/FRAX/data.json
{
  "name": "Frax",
  "symbol": "FRAX",
  "decimals": 18,
  "description": "Frax is a fractional-algorithmic stablecoin protocol. It aims to provide a highly scalable, decentralized, algorithmic money in place of fixed-supply assets like BTC. Additionally, FXS is the value accrual and governance token of the entire Frax ecosystem.",
  "website": "https://app.frax.finance/",
  "twitter": "@fraxfinance",
  "tokens": {
    "ethereum": {
      "address": "0x853d955aCEf822Db058eb8505911ED77F175b99e",
      "bridge": {
        "bob": "0x3F6cE1b36e5120BBc59D0cFe8A5aC8b6464ac1f7"
      }
    },
    "bob": {
      "address": "0xc4a20a608616F18aA631316eEDa9Fb62d089361e",
      "bridge": {
        "ethereum": "0x4200000000000000000000000000000000000010"
      }
    },
    "op-mainnet": {
      "address": "0x2E3D870790dC77A83DD1d18184Acc7439A53f475"
    }
  }
}

=== bob-collective/bob/tokenlist/data/SOV/data.json
{
  "name": "SOV",
  "symbol": "SOV",
  "decimals": 18,
  "tokens": {
    "ethereum": {
      "address": "0xbdab72602e9AD40FC6a6852CAf43258113B8F7a5",
      "bridge": {
        "bob": "0x3F6cE1b36e5120BBc59D0cFe8A5aC8b6464ac1f7"
      }
    },
    "bob": {
      "address": "0xba20a5e63eeEFfFA6fD365E7e540628F8fC61474",
      "bridge": {
        "ethereum": "0x4200000000000000000000000000000000000010"
      }
    }
  }
}

=== bob-collective/bob/tokenlist/data/TRB/data.json
{
  "name": "Tellor Tributes",
  "symbol": "TRB",
  "decimals": 18,
  "tokens": {
    "ethereum": {
      "address": "0x88df592f8eb5d7bd38bfef7deb0fbc02cf3778a0",
      "bridge": {
        "bob": "0x3F6cE1b36e5120BBc59D0cFe8A5aC8b6464ac1f7"
      }
    },
    "bob": {
      "address": "0x665060707c3Ea3c31b3eaBaD7F409072446E1D50",
      "bridge": {
        "ethereum": "0x4200000000000000000000000000000000000010"
      }
    },
    "op-mainnet": {
      "address": "0xaf8ca653fa2772d58f4368b0a71980e9e3ceb888"
    },
    "base": {
      "address": "0xF8e9E61FFB2b491f7DF29823a76009743671CD96"
    }
  }
}

=== bob-collective/bob/tokenlist/data/WETH/data.json
{
  "name": "Wrapped Ether",
  "symbol": "WETH",
  "decimals": 18,
  "tokens": {
    "ethereum": {
      "address": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
      "bridge": {
        "bob": "0x3F6cE1b36e5120BBc59D0cFe8A5aC8b6464ac1f7"
      }
    },
    "sepolia": {
      "address": "0x7b79995e5f793A07Bc00c21412e50Ecae098E7f9"
    },
    "bob": {
      "address": "0x4200000000000000000000000000000000000006",
      "bridge": { "ethereum": "0x4200000000000000000000000000000000000010" }
    },
    "bob-sepolia": {
      "address": "0x4200000000000000000000000000000000000006"
    },
    "op-mainnet": {
      "address": "0x4200000000000000000000000000000000000006"
    },
    "base": {
      "address": "0x4200000000000000000000000000000000000006"
    }
  }
}
