=== bob-collective/bob/tokenlist/token.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Token Schema",
  "type": "object",
  "definitions": {
    "ChainProperties": {
      "type": "object",
      "properties": {
        "name": {
          "$ref": "#/definitions/Name"
        },
        "symbol": {
          "$ref": "#/definitions/Symbol"
        },
        "address": {
          "$ref": "#/definitions/Address"
        },
        "bridge": {
          "type": "object",
          "properties": {
            "bob": {
              "$ref": "#/definitions/Address"
            },
            "bob-sepolia": {
              "$ref": "#/definitions/Address"
            },
            "ethereum": {
              "$ref": "#/definitions/Address"
            },
            "sepolia": {
              "$ref": "#/definitions/Address"
            },
            "bnb-smart-chain": {
              "$ref": "#/definitions/Address"
            },
            "base": {
              "$ref": "#/definitions/Address"
            },
            "op-mainnet": {
              "$ref": "#/definitions/Address"
            },
            "arbitrum-one": {
              "$ref": "#/definitions/Address"
            },
            "polygon": {
              "$ref": "#/definitions/Address"
            },
            "avalanche": {
              "$ref": "#/definitions/Address"
            },
            "unichain": {
              "$ref": "#/definitions/Address"
            },
            "sonic": {
              "$ref": "#/definitions/Address"
            },
            "sei-network": {
              "$ref": "#/definitions/Address"
            },
            "soneium-mainnet": {
              "$ref": "#/definitions/Address"
            },
            "berachain": {
              "$ref": "#/definitions/Address"
            },
            "swellchain": {
              "$ref": "#/definitions/Address"
            },
            "telos": {
              "$ref": "#/definitions/Address"
            }
          }
        },
        "overrides": {
          "type": "object",
          "properties": {
            "name": {
              "$ref": "#/definitions/Name"
            },
            "symbol": {
              "$ref": "#/definitions/Symbol"
            }
          }
        }
      },
      "required": ["address"],
      "additionalProperties": false
    },
    "Address": {
      "type": "string",
      "description": "The checksummed address of the token on the specified chain ID",
      "pattern": "^(0x[a-fA-F0-9]{40}|[1-9A-HJ-NP-Za-km-z]{32,44})$",
      "examples": [
        "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
        "So11111111111111111111111111111111111111112"
      ]
    },
    "Name": {
      "type": "string",
      "description": "The name of the token",
      "minLength": 0,
      "maxLength": 60,
      "anyOf": [
        {
          "const": ""
        },
        {
          "pattern": "^[ \\S+]+$"
        }
      ],
      "examples": ["USD Coin"]
    },
    "Symbol": {
      "type": "string",
      "description": "The symbol for the token",
      "minLength": 0,
      "maxLength": 20,
      "anyOf": [
        {
          "const": ""
        },
        {
          "pattern": "^\\S+$"
        }
      ],
      "examples": ["USDC"]
    }
  },
  "properties": {
    "name": {
      "$ref": "#/definitions/Name"
    },
    "symbol": {
      "$ref": "#/definitions/Symbol"
    },
    "decimals": {
      "type": "integer",
      "description": "The number of decimals for the token balance",
      "minimum": 0,
      "maximum": 255,
      "examples": [18]
    },
    "description": {
      "type": "string",
      "description": "A description of the token or project (can be empty)"
    },
    "website": {
      "type": "string",
      "description": "URL of the project's website",
      "format": "uri",
      "pattern": "^https?://.+"
    },
    "twitter": {
      "type": "string",
      "description": "Twitter handle of the project, e.g., '@gobob'",
      "pattern": "^@?[A-Za-z0-9_]+$"
    },
    "tokens": {
      "type": "object",
      "description": "Network-specific token addresses",
      "properties": {
        "bob": {
          "$ref": "#/definitions/ChainProperties"
        },
        "bob-sepolia": {
          "$ref": "#/definitions/ChainProperties"
        },
        "ethereum": {
          "$ref": "#/definitions/ChainProperties"
        },
        "sepolia": {
          "$ref": "#/definitions/ChainProperties"
        },
        "bnb-smart-chain": {
          "$ref": "#/definitions/ChainProperties"
        },
        "base": {
          "$ref": "#/definitions/ChainProperties"
        },
        "op-mainnet": {
          "$ref": "#/definitions/ChainProperties"
        },
        "arbitrum-one": {
          "$ref": "#/definitions/ChainProperties"
        },
        "polygon": {
          "$ref": "#/definitions/ChainProperties"
        },
        "avalanche": {
          "$ref": "#/definitions/ChainProperties"
        },
        "unichain": {
          "$ref": "#/definitions/ChainProperties"
        },
        "sonic": {
          "$ref": "#/definitions/ChainProperties"
        },
        "sei-network": {
          "$ref": "#/definitions/ChainProperties"
        },
        "soneium-mainnet": {
          "$ref": "#/definitions/ChainProperties"
        },
        "berachain": {
          "$ref": "#/definitions/ChainProperties"
        },
        "swellchain": {
          "$ref": "#/definitions/ChainProperties"
        },
        "telos": {
          "$ref": "#/definitions/ChainProperties"
        }
      },
      "minProperties": 1,
      "additionalProperties": false
    }
  },
  "required": ["name", "symbol", "decimals", "tokens"],
  "additionalProperties": false
}

=== bob-collective/bob/tokenlist/data/sfrxETH/data.json
{
  "name": "Staked Frax Ether",
  "symbol": "sfrxETH",
  "decimals": 18,
  "website": "https://frax.finance/",
  "description": "sfrxETH is the version of frxETH which accrues staking yield. All profit generated from Frax Ether validators is distributed to sfrxETH holders. By exchanging frxETH for sfrxETH, one become's eligible for staking yield, which is redeemed upon converting sfrxETH back to frxETH.",
  "twitter": "@fraxfinance",
  "tokens": {
    "ethereum": {
      "address": "0xac3E018457B222d93114458476f3E3416Abbe38F",
      "bridge": {
        "bob": "0x3F6cE1b36e5120BBc59D0cFe8A5aC8b6464ac1f7"
      }
    },
    "bob": {
      "address": "0x249d2952D1C678843e7cD7bF654EfCeC52f2F9E8",
      "bridge": {
        "ethereum": "0x4200000000000000000000000000000000000010"
      }
    },
    "op-mainnet": {
      "address": "0x484c2D6e3cDd945a8B2DF735e079178C1036578c"
    }
  }
}

=== bob-collective/bob/tokenlist/data/FBTC/data.json
{
  "name": "Fire Bitcoin",
  "symbol": "FBTC",
  "decimals": 8,
  "tokens": {
    "ethereum": {
      "address": "0xC96dE26018A54D51c097160568752c4E3BD6C364",
      "bridge": {
        "bob": "0x3F6cE1b36e5120BBc59D0cFe8A5aC8b6464ac1f7"
      }
    },
    "bob": {
      "address": "0xC96dE26018A54D51c097160568752c4E3BD6C364",
      "bridge": {
        "ethereum": "0x4200000000000000000000000000000000000010"
      }
    }
  }
}

=== bob-collective/bob/tokenlist/data/rETH/data.json
{
  "name": "Rocket Pool ETH",
  "symbol": "rETH",
  "decimals": 18,
  "website": "https://rocketpool.net/",
  "twitter": "@Rocket_Pool",
  "tokens": {
    "ethereum": {
      "address": "0xae78736cd615f374d3085123a210448e74fc6393",
      "bridge": {
        "bob": "0x3F6cE1b36e5120BBc59D0cFe8A5aC8b6464ac1f7"
      }
    },
    "bob": {
      "address": "0xB5686c4f60904Ec2BDA6277d6FE1F7cAa8D1b41a",
      "bridge": {
        "ethereum": "0x4200000000000000000000000000000000000010"
      }
    },
    "op-mainnet": {
      "address": "0x9bcef72be871e61ed4fbbc7630889bee758eb81d"
    },
    "base": {
      "address": "0xB6fe221Fe9EeF5aBa221c348bA20A1Bf5e73624c"
    }
  }
}

=== bob-collective/bob/tokenlist/data/UNI/data.json
{
  "name": "Uniswap",
  "symbol": "UNI",
  "decimals": 18,
  "tokens": {
    "ethereum": {
      "address": "0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984",
      "bridge": {
        "bob": "0x3F6cE1b36e5120BBc59D0cFe8A5aC8b6464ac1f7"
      }
    },
    "bob": {
      "address": "0x6fD31f56eb971113bEA12C5883deC68337b3B7b5",
      "bridge": {
        "ethereum": "0x4200000000000000000000000000000000000010"
      }
    },
    "op-mainnet": {
      "address": "0x6fd9d7AD17242c41f7131d257212c54A0e816691"
    },
    "base": {
      "address": "0xc3De830EA07524a0761646a6a4e4be0e114a3C83"
    }
  }
}

=== bob-collective/bob/tokenlist/data/ETH/data.json
{
  "name": "Ether",
  "symbol": "ETH",
  "decimals": 18,
  "tokens": {
    "ethereum": {
      "address": "0x0000000000000000000000000000000000000000"
    },
    "sepolia": {
      "address": "0x0000000000000000000000000000000000000000"
    },
    "bob": {
      "address": "0x0000000000000000000000000000000000000000"
    },
    "bob-sepolia": {
      "address": "0x0000000000000000000000000000000000000000"
    },
    "bnb-smart-chain": {
      "address": "0x0000000000000000000000000000000000000000",
      "overrides": {
        "name": "BNB",
        "symbol": "BNB"
      }
    }
  }
}

=== bob-collective/bob/tokenlist/data/FXS/data.json
{
  "name": "Frax Share",
  "symbol": "FXS",
  "decimals": 18,
  "description": "Frax Shares (FXS) is the seigniorage token in the Frax protocol.",
  "website": "https://app.frax.finance/",
  "twitter": "@fraxfinance",
  "tokens": {
    "ethereum": {
      "address": "0x3432B6A60D23Ca0dFCa7761B7ab56459D9C964D0"
    },

    "bob": {
      "address": "0x15e35B19AD29C512103EaABb55154Ef0Ee6ca661"
    },
    "op-mainnet": {
      "address": "0x67CCEA5bb16181E7b4109c9c2143c24a1c2205Be"
    }
  }
}

=== bob-collective/bob/tokenlist/data/WBTCOFT/data.json
{
  "name": "Wrapped BTC",
  "symbol": "WBTC",
  "decimals": 8,
  "description": "Wrapped Bitcoin delivers the power of Bitcoin with the flexibility of an ERC20 token",
  "website": "https://layerzero.network",
  "twitter": "@layerzero_core",
  "tokens": {
    "ethereum": {
      "address": "0x0555E30da8f98308EdB960aa94C0Db47230d2B9c"
    },
    "bob": {
      "address": "0x0555E30da8f98308EdB960aa94C0Db47230d2B9c"
    },
    "bnb-smart-chain": {
      "address": "0x0555e30da8f98308edb960aa94c0db47230d2b9c"
    },
    "op-mainnet": {
      "address": "0xc3f854b2970f8727d28527ece33176fac67fef48"
    },
    "base": {
      "address": "0x0555e30da8f98308edb960aa94c0db47230d2b9c"
    },
    "avalanche": {
      "address": "0x0555e30da8f98308edb960aa94c0db47230d2b9c"
    },
    "swellchain": {
      "address": "0x0555e30da8f98308edb960aa94c0db47230d2b9c"
    },
    "sei-network": {
      "address": "0x0555e30da8f98308edb960aa94c0db47230d2b9c"
    },
    "soneium-mainnet": {
      "address": "0x0555e30da8f98308edb960aa94c0db47230d2b9c"
    },
    "berachain": {
      "address": "0x0555e30da8f98308edb960aa94c0db47230d2b9c"
    },
    "unichain": {
      "address": "0x0555e30da8f98308edb960aa94c0db47230d2b9c"
    },
    "sonic": {
      "address": "0x0555e30da8f98308edb960aa94c0db47230d2b9c"
    },
    "telos": {
      "address": "0x0555e30da8f98308edb960aa94c0db47230d2b9c"
    }
  }
}
