=== bob-collective/bob/tokenlist/token.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Token Schema",
  "type": "object",
  "definitions": {
    "ChainProperties": {
      "type": "object",
      "properties": {
        "name": {
          "$ref": "#/definitions/Name"
        },
        "symbol": {
          "$ref": "#/definitions/Symbol"
        },
        "address": {
          "$ref": "#/definitions/Address"
        },
        "bridge": {
          "type": "object",
          "properties": {
            "bob": {
              "$ref": "#/definitions/Address"
            },
            "bob-sepolia": {
              "$ref": "#/definitions/Address"
            },
            "ethereum": {
              "$ref": "#/definitions/Address"
            },
            "sepolia": {
              "$ref": "#/definitions/Address"
            },
            "bnb-smart-chain": {
              "$ref": "#/definitions/Address"
            },
            "base": {
              "$ref": "#/definitions/Address"
            },
            "op-mainnet": {
              "$ref": "#/definitions/Address"
            },
            "arbitrum-one": {
              "$ref": "#/definitions/Address"
            },
            "polygon": {
              "$ref": "#/definitions/Address"
            },
            "avalanche": {
              "$ref": "#/definitions/Address"
            },
            "unichain": {
              "$ref": "#/definitions/Address"
            },
            "sonic": {
              "$ref": "#/definitions/Address"
            },
            "sei-network": {
              "$ref": "#/definitions/Address"
            },
            "soneium-mainnet": {
              "$ref": "#/definitions/Address"
            },
            "berachain": {
              "$ref": "#/definitions/Address"
            },
            "swellchain": {
              "$ref": "#/definitions/Address"
            },
            "telos": {
              "$ref": "#/definitions/Address"
            }
          }
        },
        "overrides": {
          "type": "object",
          "properties": {
            "name": {
              "$ref": "#/definitions/Name"
            },
            "symbol": {
              "$ref": "#/definitions/Symbol"
            }
          }
        }
      },
      "required": ["address"],
      "additionalProperties": false
    },
    "Address": {
      "type": "string",
      "description": "The checksummed address of the token on the specified chain ID",
      "pattern": "^(0x[a-fA-F0-9]{40}|[1-9A-HJ-NP-Za-km-z]{32,44})$",
      "examples": [
        "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
        "So11111111111111111111111111111111111111112"
      ]
    },
    "Name": {
      "type": "string",
      "description": "The name of the token",
      "minLength": 0,
      "maxLength": 60,
      "anyOf": [
        {
          "const": ""
        },
        {
          "pattern": "^[ \\S+]+$"
        }
      ],
      "examples": ["USD Coin"]
    },
    "Symbol": {
      "type": "string",
      "description": "The symbol for the token",
      "minLength": 0,
      "maxLength": 20,
      "anyOf": [
        {
          "const": ""
        },
        {
          "pattern": "^\\S+$"
        }
      ],
      "examples": ["USDC"]
    }
  },
  "properties": {
    "name": {
      "$ref": "#/definitions/Name"
    },
    "symbol": {
      "$ref": "#/definitions/Symbol"
    },
    "decimals": {
      "type": "integer",
      "description": "The number of decimals for the token balance",
      "minimum": 0,
      "maximum": 255,
      "examples": [18]
    },
    "description": {
      "type": "string",
      "description": "A description of the token or project (can be empty)"
    },
    "website": {
      "type": "string",
      "description": "URL of the project's website",
      "format": "uri",
      "pattern": "^https?://.+"
    },
    "twitter": {
      "type": "string",
      "description": "Twitter handle of the project, e.g., '@gobob'",
      "pattern": "^@?[A-Za-z0-9_]+$"
    },
    "tokens": {
      "type": "object",
      "description": "Network-specific token addresses",
      "properties": {
        "bob": {
          "$ref": "#/definitions/ChainProperties"
        },
        "bob-sepolia": {
          "$ref": "#/definitions/ChainProperties"
        },
        "ethereum": {
          "$ref": "#/definitions/ChainProperties"
        },
        "sepolia": {
          "$ref": "#/definitions/ChainProperties"
        },
        "bnb-smart-chain": {
          "$ref": "#/definitions/ChainProperties"
        },
        "base": {
          "$ref": "#/definitions/ChainProperties"
        },
        "op-mainnet": {
          "$ref": "#/definitions/ChainProperties"
        },
        "arbitrum-one": {
          "$ref": "#/definitions/ChainProperties"
        },
        "polygon": {
          "$ref": "#/definitions/ChainProperties"
        },
        "avalanche": {
          "$ref": "#/definitions/ChainProperties"
        },
        "unichain": {
          "$ref": "#/definitions/ChainProperties"
        },
        "sonic": {
          "$ref": "#/definitions/ChainProperties"
        },
        "sei-network": {
          "$ref": "#/definitions/ChainProperties"
        },
        "soneium-mainnet": {
          "$ref": "#/definitions/ChainProperties"
        },
        "berachain": {
          "$ref": "#/definitions/ChainProperties"
        },
        "swellchain": {
          "$ref": "#/definitions/ChainProperties"
        },
        "telos": {
          "$ref": "#/definitions/ChainProperties"
        }
      },
      "minProperties": 1,
      "additionalProperties": false
    }
  },
  "required": ["name", "symbol", "decimals", "tokens"],
  "additionalProperties": false
}

=== bob-collective/bob/tokenlist/data/pumpBTC/data.json
{
  "name": "pumpBTC",
  "symbol": "pumpBTC",
  "decimals": 8,
  "description": "",
  "tokens": {
    "ethereum": {
      "address": "0xF469fBD2abcd6B9de8E169d128226C0Fc90a012e",
      "bridge": {
        "bob": "0x3F6cE1b36e5120BBc59D0cFe8A5aC8b6464ac1f7"
      }
    },
    "bob": {
      "address": "0x1fCca65fb6Ae3b2758b9b2B394CB227eAE404e1E",
      "bridge": {
        "ethereum": "0x4200000000000000000000000000000000000010"
      }
    }
  }
}

=== bob-collective/bob/tokenlist/data/sFRAX/data.json
{
  "name": "Staked Frax",
  "symbol": "sFRAX",
  "decimals": 18,
  "tokens": {
    "ethereum": {
      "address": "0xA663B02CF0a4b149d2aD41910CB81e23e1c41c32",
      "bridge": {
        "bob": "0x3F6cE1b36e5120BBc59D0cFe8A5aC8b6464ac1f7"
      }
    },
    "bob": {
      "address": "0xb7eae04B995B3b365040dEE99795112ADD43afa0",
      "bridge": {
        "ethereum": "0x4200000000000000000000000000000000000010"
      }
    }
  }
}

=== bob-collective/bob/tokenlist/data/uniBTC/data.json
{
  "name": "uniBTC",
  "symbol": "uniBTC",
  "decimals": 8,
  "description": "",
  "website": "https://www.bedrock.technology/",
  "twitter": "@Bedrock_DeFi",
  "tokens": {
    "ethereum": {
      "address": "0x004e9c3ef86bc1ca1f0bb5c7662861ee93350568"
    },
    "bob": {
      "address": "0x236f8c0a61dA474dB21B693fB2ea7AAB0c803894"
    },
    "op-mainnet": {
      "address": "0x93919784c523f39cacaa98ee0a9d96c3f32b593e"
    },
    "arbitrum-one": {
      "address": "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
    },
    "base": {
      "address": "0x93919784c523f39cacaa98ee0a9d96c3f32b593e"
    },
    "bnb-smart-chain": {
      "address": "0x6b2a01a5f79deb4c2f3c0eda7b01df456fbd726a"
    }
  }
}

=== bob-collective/bob/tokenlist/data/xSolvBTC/data.json
{
  "name": "xSolvBTC",
  "symbol": "xSolvBTC",
  "decimals": 18,
  "description": "",
  "website": "https://app.solv.finance/",
  "twitter": "@SolvProtocol",
  "tokens": {
    "ethereum": {
      "address": "0xd9D920AA40f578ab794426F5C90F6C731D159DEf"
    },
    "bob": {
      "address": "0xCC0966D8418d412c599A6421b760a847eB169A8c"
    },
    "bnb-smart-chain": {
      "address": "0x1346b618dc92810ec74163e4c27004c921d446a5"
    },
    "avalanche": {
      "address": "0xcc0966d8418d412c599a6421b760a847eb169a8c"
    },
    "base": {
      "address": "0xc26c9099bd3789107888c35bb41178079b282561"
    },
    "arbitrum-one": {
      "address": "0x346c574c56e1a4aaa8dc88cda8f7eb12b39947ab"
    },
    "polygon": {
      "address": "0xc99f5c922dae05b6e2ff83463ce705ef7c91f077"
    }
  }
}

=== bob-collective/bob/tokenlist/data/BOB/data.json
{
  "name": "BOB",
  "symbol": "BOB",
  "decimals": 18,
  "description": "",
  "website": "https://app.gobob.xyz/",
  "twitter": "@build_on_bob",
  "tokens": {
    "ethereum": {
      "address": "0xC9746F73cC33a36c2cD55b8aEFD732586946Cedd",
      "bridge": {
        "bob": "0x80226fc0Ee2b096224EeAc085Bb9a8cba1146f7D",
        "bnb-smart-chain": "0x80226fc0Ee2b096224EeAc085Bb9a8cba1146f7D"
      }
    },
    "bob": {
      "address": "0xb0bd54846a92b214c04a63b26ad7dc5e19a60808",
      "bridge": {
        "ethereum": "0x827716e74F769AB7b6bb374A29235d9c2156932C",
        "bnb-smart-chain": "0x827716e74F769AB7b6bb374A29235d9c2156932C"
      }
    },
    "bob-sepolia": {
      "address": "0x49D6FBFa3Ee5462626D65Cd22FC0CFb03ed907DB"
    },
    "bnb-smart-chain": {
      "address": "0x52B5fB4B0F6572B8C44d0251Cc224513ac5eB7E7",
      "bridge": {
        "ethereum": "0x34B03Cb9086d7D758AC55af71584F81A598759FE",
        "bob": "0x34B03Cb9086d7D758AC55af71584F81A598759FE"
      }
    }
  }
}

=== bob-collective/bob/tokenlist/data/wstETH/data.json
{
  "name": "Wrapped liquid staked Ether 2.0",
  "symbol": "wstETH",
  "decimals": 18,
  "tokens": {
    "ethereum": {
      "address": "0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0",
      "bridge": {
        "bob": "0x091dF5E1284E49fA682407096aD34cfD42B95B72"
      }
    },
    "sepolia": {
      "address": "0xB82381A3fBD3FaFA77B3a7bE693342618240067b"
    },
    "bob": {
      "address": "0x85008aE6198BC91aC0735CB5497CF125ddAAc528",
      "bridge": {
        "ethereum": "0xd1559523374D93972E0F7fE1AA98642754f5c4d1"
      }
    },
    "op-mainnet": {
      "address": "0x1F32b1c2345538c0c6f582fCB022739c4A194Ebb"
    },
    "base": {
      "address": "0xc1CBa3fCea344f92D9239c08C0568f6F2F0ee452"
    }
  }
}

=== bob-collective/bob/tokenlist/data/STONE/data.json
{
  "name": "StakeStone Ether",
  "symbol": "STONE",
  "decimals": 18,
  "tokens": {
    "ethereum": {
      "address": "0x7122985656e38BDC0302Db86685bb972b145bD3C",
      "bridge": {
        "bob": "0x3F6cE1b36e5120BBc59D0cFe8A5aC8b6464ac1f7"
      }
    },
    "bob": {
      "address": "0x96147A9Ae9a42d7Da551fD2322ca15B71032F342",
      "bridge": {
        "ethereum": "0x4200000000000000000000000000000000000010"
      }
    }
  }
}

=== bob-collective/bob/tokenlist/data/WBTC/data.json
{
  "name": "Wrapped BTC",
  "symbol": "WBTC",
  "decimals": 8,
  "description": "Wrapped Bitcoin delivers the power of Bitcoin with the flexibility of an ERC20 token",
  "website": "https://wbtc.network/",
  "twitter": "@WrappedBTC",
  "tokens": {
    "ethereum": {
      "address": "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599",
      "bridge": {
        "bob": "0x3F6cE1b36e5120BBc59D0cFe8A5aC8b6464ac1f7"
      }
    },
    "bob": {
      "address": "0x03C7054BCB39f7b2e5B2c7AcB37583e32D70Cfa3",
      "bridge": {
        "ethereum": "0x4200000000000000000000000000000000000010"
      },
      "overrides": {
        "name": "Bridged WBTC"
      }
    },
    "arbitrum-one": {
      "address": "0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f"
    },
    "op-mainnet": {
      "address": "0x68f180fcce6836688e9084f035309e29bf0a2095"
    }
  }
}
